### ISSUE TITLE
好好准备中考，编程人生路漫漫

### ISSUE THREAD

**Issue by arjinmc** [xiaoland/xiaolan#2]
谷歌开发者大会看到你的演讲，看好你，小伙子。——来自一个工作多年的coder。

**Comment by xiaoland** [comment]
谢谢~！
说实话那次演讲好糟糕...
不过现在中考已经考完了，托您的福，考的还不错

**Comment by arjinmc** [comment]
我啥也没做，都是你自己的努力。继续加油。
